server:
  host: "0.0.0.0"
  port: 8000
  log_level: "info"
  reload: true
  workers: 1

candidate_generations:
  - 
    prompt_type: "direct_generation"
    query_validation_kwargs:
      model: "google_genai:gemini-2.0-flash"
    generation_kwargs:
      model: "google_genai:gemini-2.0-flash"
    query_fixer_kwargs:
      model: "google_genai:gemini-2.0-flash"
  -
    prompt_type: "cot_generation"
    query_validation_kwargs:
      model: "google_genai:gemini-2.0-flash"
    generation_kwargs:
      model: "google_genai:gemini-2.0-flash"
    query_fixer_kwargs:
      model: "google_genai:gemini-2.0-flash"
  -
    prompt_type: "query_plan_generation"
    query_validation_kwargs:
      model: "google_genai:gemini-2.0-flash"
    generation_kwargs:
      model: "google_genai:gemini-2.0-flash"
    query_fixer_kwargs:
      model: "google_genai:gemini-2.0-flash"

merger:
  model: "google_genai:gemini-2.0-flash"

result_enhancement:
  model: "mistralai:mistral-small-latest"

schema_linking:
  model: "google_genai:gemini-2.0-flash"