[project]
name = "sql-qa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "langchain-community>=0.3.22",
    "langchain[mistralai,openai]>=0.3.24",
    "langgraph>=0.3.34",
    "pymysql>=1.1.1",
    "pytest>=8.3.5",
]

[tool.uv.workspace]
members = ["shared"]
